### ISSUE TITLE
聊天内容的缩放是否可以控制?

### ISSUE THREAD

**Issue by seakingii** [xiaorui-23/chat_flutter#2]
测试版本: 2.0.2

在WINDOWS上,当前宽度不是设计比例时,内容会放大到夸张的程度

请问:是否有方法不要自动缩放

<img width="1025" alt="2" src="https://github.com/xiaorui-23/chat_flutter/assets/1295203/211201ae-614f-48a8-bfbb-eec500cc1331">

**Comment by xiaorui-23** [comment]
> 测试版：2.0.2
> 
> 在WINDOWS上，当之前的广度不是设计比例时，内容会放大到夸张的程度
> 
> 请问:是不是有方法不要自动缩小
> 
> <img alt="2个" width="1025" src="https://user-images.githubusercontent.com/1295203/240982996-211201ae-614f-48a8-bfbb-eec500cc1331.png">


您好。你可以通过自定义头像或者传递头像大小进行控制尺寸；内容主体部分你可以自定义内容主体。目前并没有其他的参数或者api控制是否需要自适应。

**Comment by xiaorui-23** [comment]
> 测试版本: 2.0.2
> 
> 在WINDOWS上,当前宽度不是设计比例时,内容会放大到夸张的程度
> 
> 请问:是否有方法不要自动缩放
> 
> <img alt="2" width="1025" src="https://user-images.githubusercontent.com/1295203/240982996-211201ae-614f-48a8-bfbb-eec500cc1331.png">

鉴于您未对此问题进行进一步的回复，我将关闭该问题，后续在使用的过程中有任何的疑问和问题可以再次创建一个新的 `issues` 进行提问和联系，感谢您对 `chat_flutter` 及我的支持。
